monitors:
  default:
    position: top
    height: 38
    margin:
      top: 5
      left: 10
      right: 10
    start:
      - type: workspaces
        all_outputs: false # Shows only workspaces on the current monitor
        format: "{icon}"
        format-icons:
          focused: ""
          active: ""
          default: ""
          empty: "◌"
    center:
      - type: focused
        format: "{title}" # Shows the active Niri window title
        truncate:
          mode: end
          length: 50
    end:
      - type: tray
      - type: sys_info
        format: " {cpu_percent}%   {memory_percent}%"
      - type: clock
        format: "%H:%M"
